// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEymnHdxHURyNh6UNPKdaMyACkUL1Sr1s',
    appId: '1:324187337332:web:c8b1c5999c120ab8285721',
    messagingSenderId: '324187337332',
    projectId: 'musikat-app',
    authDomain: 'musikat-app.firebaseapp.com',
    storageBucket: 'musikat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0dYQjN-QpSM1G9_IXrzWr52MrLnZ-c4o',
    appId: '1:324187337332:android:700e4015a8531340285721',
    messagingSenderId: '324187337332',
    projectId: 'musikat-app',
    storageBucket: 'musikat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAf59vJzSrhUoRQ7t6RVkHlV9Fxu04n34',
    appId: '1:324187337332:ios:4cf19967aeeaed89285721',
    messagingSenderId: '324187337332',
    projectId: 'musikat-app',
    storageBucket: 'musikat-app.appspot.com',
    iosClientId: '324187337332-g1nk20vh31f1thp107u7pothohn5cs0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.musikatApp',
  );
}
